
name: Build SMTube 64 bits

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install sources
        run: .\download_smtube.cmd
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          arch: 'win64_mingw81'
         
      - name: Download QtWebkit
        run: Invoke-WebRequest -Uri https://github.com/qtwebkit/qtwebkit/releases/download/qtwebkit-5.212.0-alpha4/qtwebkit-Windows-Windows_10-Mingw73-Windows-Windows_10-X86_64.7z -OutFile qtwebkit.7z

      - name: Extract QtWebKit
        shell: bash
        run: 7z x qtwebkit.7z -o$Qt5_Dir
     
      - name: Build smtube
        run: .\build_smtube.cmd

      - name: Get installer name
        shell: bash
        run: |
            filename=`cd packages/smtube/setup/output/ ; ls smtube*.exe | head -1`
            echo $filename
            echo "INSTALLERFILENAME=$filename" >> $GITHUB_ENV
        
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.INSTALLERFILENAME }}
          path: packages\smtube\setup\output\smtube*.exe
