name: Build SMTube Windows

on: workflow_dispatch

jobs:
  build-32:
    name: Build 32 bit
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install sources
        run: .\download_smtube.cmd

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          arch: 'win32_mingw81'
          tools: 'tools_mingw,8.1.0-1,qt.tools.win32_mingw810'

      - name: Download QtWebkit
        run: Invoke-WebRequest -Uri https://github.com/qtwebkit/qtwebkit/releases/download/qtwebkit-5.212.0-alpha4/qtwebkit-Windows-Windows_7-Mingw73-Windows-Windows_7-X86.7z -OutFile qtwebkit.7z

      - name: Extract QtWebKit
        shell: bash
        run: 7z x qtwebkit.7z -o$Qt5_Dir

      - name: Set mingw32 path
        run: echo "$env:IQTA_TOOLS\mingw810_32\bin\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build smtube
        run: .\build_smtube.cmd

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: smtube-win32
          path: packages\smtube\setup\output\

  build-64:
    name: Build 64 bit  
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install sources
        run: .\download_smtube.cmd

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          arch: 'win64_mingw81'

      - name: Download QtWebkit
        run: Invoke-WebRequest -Uri https://github.com/qtwebkit/qtwebkit/releases/download/qtwebkit-5.212.0-alpha4/qtwebkit-Windows-Windows_10-Mingw73-Windows-Windows_10-X86_64.7z -OutFile qtwebkit.7z

      - name: Extract QtWebKit
        shell: bash
        run: 7z x qtwebkit.7z -o$Qt5_Dir

      - name: Build smtube
        run: .\build_smtube.cmd

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: smtube-x64
          path: packages\smtube\setup\output\
