name: Build SMPlayer 64 bits on Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install sources
        run: .\download_packages.cmd
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: 'win64_mingw81'
          tools: 'tools_openssl_x64,1.1.1-1,qt.tools.openssl.win_x64'
          #tools: 'tools_openssl_x86,1.1.1-1,qt.tools.openssl.win_x86'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          
      - name: Compile themes
        run: .\compile_themes.cmd
        
      - name: Compile smplayer
        run: .\compile_smplayer.cmd
        #run: |
        #    #dir packages
        #    #dir packages\smplayer\src
        #    mkdir packages\smplayer\src\release
        #    echo nul > packages\smplayer\src\release\smplayer.exe

      - name: Install
        run: |
            .\install.cmd
            dir packages\BUILD\
        
      - name: Create installer
        run: |
           .\nsis.cmd
           $filename = Get-Content packages\BUILD\installer_filename.txt -TotalCount 1
           echo "INSTALLERFILENAME=$filename" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.INSTALLERFILENAME }}
          path: packages\BUILD\output\${{ env.INSTALLERFILENAME }}
