name: Build SMPlayer on Windows

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install sources
        run: .\download_packages.cmd
      
      - name: List
        run: dir packages
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: 'win64_mingw81'
          tools: 'tools_openssl_x64,1.1.1-1,qt.tools.openssl.win_x64 tools_openssl_x86,1.1.1-1,qt.tools.openssl.win_x86'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          
      - name: Compile themes
        run: .\compile_themes.cmd
        
