name: Build SMPlayer with Qt 5.6
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: 'win32', 'portable': false }
          - { arch: 'win32', 'portable': true }

    runs-on: windows-latest
    env:
      PORTABLE: ${{ matrix.config.portable }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Qt 5.6
        shell: bash
        run: |
            choco install wget --no-progress
            wget -nv https://github.com/smplayer-dev/smplayer-build/releases/download/qt5.6.3/Qt5.6.3_mingw493_32-563-p-dwarf2-opengl_dynamic.7z -O Qt5.6z
            7z x Qt5.6z -oQt5
            # Set environment variables
            export MinGW_Bin_Path=$GITHUB_WORKSPACE/Qt5/mingw32/bin
            export Qt_Bin_Path=$GITHUB_WORKSPACE/Qt5/mingw493_32-563-p-dwarf2/bin
            echo "MinGW_Bin_Path=$MinGW_Bin_Path" >> $GITHUB_ENV
            echo "Qt_Bin_Path=$Qt_Bin_Path" >> $GITHUB_ENV
            echo "$MinGW_Bin_Path" >> $GITHUB_PATH
            echo "$Qt_Bin_Path" >> $GITHUB_PATH

      - name: Install sources
        run: |
            .\download_packages.cmd
            .\uncompress_players.cmd

      - name: Compile themes
        run: .\compile_themes.cmd
        
      - name: Compile smplayer
        run: |
            if ($env:PORTABLE -eq $true) {
              .\compile_smplayer.cmd pe
            } else {
              .\compile_smplayer.cmd
            }

      - name: Install
        run: |
            if ($env:PORTABLE -eq $true) {
              .\install.cmd pe
            } else {
              .\install.cmd
            }
        
      - name: Create installer
        if: ${{ matrix.config.portable == false }}
        run: |
           .\nsis.cmd
           $filename = Get-Content packages\BUILD\installer_filename.txt -TotalCount 1
           # Rename
           cd packages\BUILD\output\
           $basename = (Get-Item $filename ).Basename
           $new_filename = "$basename-qt5.6.exe"  
           move $filename $new_filename
           echo "PACKAGEFILENAME=$new_filename" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create 7z package
        if: ${{ matrix.config.portable == true }}
        run: |
           .\create_portable_package.cmd
           $filename = Get-Content packages\BUILD\portable_filename.txt -TotalCount 1
           echo "PACKAGEFILENAME=$filename" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGEFILENAME }}
          path: packages\BUILD\output\${{ env.PACKAGEFILENAME }}
