name: Build SMPlayer 64 bits

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install sources
        run: .\download_packages.cmd

      - name: Install mplayer and mpv
        run: .\uncompress_players.cmd

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          arch: 'win64_mingw81'
          #tools: 'tools_openssl_x64,1.1.1-1,qt.tools.openssl.win_x64'
          tools: 'tools_opensslv3_x64,3.0.11-1,qt.tools.opensslv3.win_x64'
          
      - name: Compile themes
        run: .\compile_themes.cmd
        
      - name: Compile smplayer
        run: .\compile_smplayer.cmd

      - name: Install
        run: .\install.cmd
        
      - name: Create installer
        run: |
           .\nsis.cmd
           $filename = Get-Content packages\BUILD\installer_filename.txt -TotalCount 1
           echo "INSTALLERFILENAME=$filename" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Rename package
        shell: bash
        run: |
           installer=${{env.INSTALLERFILENAME}}
           filename=${installer/.exe/-unsigned.exe}
           mv packages/BUILD/output/$installer packages/BUILD/output/$filename
           echo "INSTALLERFILENAME=$filename" >> $GITHUB_ENV
      
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.INSTALLERFILENAME }}
          path: packages\BUILD\output\${{ env.INSTALLERFILENAME }}
