name: Build appimage

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    container: wachii/ubuntu-qt512:16.04

    steps:
      - name: Install sources
        run: git clone https://github.com/smplayer-dev/smplayer.git smplayer

      - name: Install linuxdeployqt
        run: |
            wget https://github.com/probonopd/linuxdeployqt/releases/download/7/linuxdeployqt-7-x86_64.AppImage
            chmod 755 linuxdeployqt-7-x86_64.AppImage

      - name: Install development packages
        run: |
            sudo apt-get update
            #sudo apt-get install zlib1g-dev fakeroot build-essential devscripts debhelper g++
            #sudo apt-get install qtbase5-dev qt5-qmake qt5-default libqt5opengl5-dev qttools5-dev-tools qtbase5-private-dev
            sudo apt-get -y install libxcb-xinerama0
            #sudo apt-get -y remove qtbase5-dev qt5-qmake qt5-default libqt5opengl5-dev qttools5-dev-tools qtbase5-private-dev libqt5webkit5-dev
            #sudo apt-get -y install python3-pip

      - name: Install Qt
        #if: ${{false}}
        run: |
            sudo add-apt-repository ppa:beineri/opt-qt-5.12.2-xenial -y
            sudo apt-get update
            sudo apt-get -y install qt512-meta-full libgl1-mesa-dev
            #source /opt/qt512/bin/qt512-env.sh

      - name: Install Qt
        if: ${{false}}
        uses: jurplel/install-qt-action@v2
        with:
          host: 'linux'

      - name: Get version
        run: |
            cd smplayer
            ./get_version.sh
            VERSION=`cat version`
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Compile smplayer
        shell: bash
        run: |
            source /opt/qt512/bin/qt512-env.sh
            cd smplayer
            ./get_svn_revision.sh
            make -j4 PREFIX=/usr QMAKE=qmake LRELEASE=lrelease \
                 QMAKE_OPTS="DEFINES+=NO_DEBUG_ON_CONSOLE DEFINES+=USE_SHM DEFINES+=USE_GL_WINDOW DEFINES+=SIMPLE_BUILD"
            
      - name: Install smplayer
        run: |
            cd smplayer
            make install DESTDIR=appdir PREFIX=/usr
            ls -lR appdir

      - name: Create package
        run: |
            cd smplayer
            ../linuxdeployqt-7-x86_64.AppImage appdir/usr/share/applications/smplayer.desktop -appimage
    
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: smplayer
          path: smplayer/*.AppImage
