name: Build SMTube with Qt 5.6
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        #if: ${{false}}
        uses: actions/checkout@v2

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: Qt5
          key: ${{ runner.os }}-qt5.6

      - name: Install Qt 5.6
        shell: bash
        #if: ${{false}}
        if: steps.cache-qt.outputs.cache-hit != 'true'
        run: |
            choco install wget --no-progress
            wget -nv https://github.com/smplayer-dev/smplayer-build/releases/download/qt5.6.3/Qt5.6.3_mingw493_32-563-p-dwarf2-opengl_dynamic.7z -O Qt5.6z
            7z x Qt5.6z -oQt5

      - name: Set environment variables
        shell: bash
        run: |
            export MinGW_Bin_Path=$GITHUB_WORKSPACE/Qt5/mingw32/bin
            export Qt_Bin_Path=$GITHUB_WORKSPACE/Qt5/mingw493_32-563-p-dwarf2/bin
            echo "MinGW_Bin_Path=$MinGW_Bin_Path" >> $GITHUB_ENV
            echo "Qt_Bin_Path=$Qt_Bin_Path" >> $GITHUB_ENV
            echo "$MinGW_Bin_Path" >> $GITHUB_PATH
            echo "$Qt_Bin_Path" >> $GITHUB_PATH

      - name: Build smtube
        run: |
            .\download_smtube.cmd
            .\build_smtube.cmd

      - name: Get installer name
        shell: bash
        run: |
            filename=`cd packages/smtube/setup/output/ ; ls smtube*.exe | head -1`
            echo "INSTALLERFILENAME=$filename" >> $GITHUB_ENV

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.INSTALLERFILENAME }}
          path: packages\smtube\setup\output\smtube*.exe
