name: Build archlinux packages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: wachii/archlinux:devel
      #options: --user user

    steps:
      - name: List
        run: ls -lR ..
      
      - name: Checkout
        #uses: actions/checkout@v2
        run: svn co https://github.com/smplayer-dev/smplayer-build.git/trunk/archlinux

      - name: Build
        run: |
            cd archlinux
            ./build_smtube.sh
            
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: smtube-archlinux
          path: archlinux/smtube-*.pkg.tar.zst
