name: Build SMPlayer Portable MSVC 64 bits

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install sources
        run: .\download_packages.cmd
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          arch: 'win64_mingw81'
          tools: 'tools_openssl_x64,1.1.1-1,qt.tools.openssl.win_x64'
      
      - name: Install Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@v1 
          
      - name: Compile themes
        run: .\compile_themes.cmd

      - name: Compile zlib   
        run: |
            cd smplayer\zlib
            nmake -f win32/Makefile.msc

      - name: Compile web server
        run: |
            cd smplayer\webserver
            nmake -f Makefile.msc

      - name: Compile smplayer
        run: |
            cd smplayer
            .\getrev.cmd
            cd src
            lrelease smplayer.pro
            qmake DEFINES+=PORTABLE_APP
            nmake

      - name: Install
        run: .\install.cmd pe
        
      - name: Create 7z package
        run: |
           .\create_portable_package.cmd
           $filename = Get-Content packages\BUILD\portable_filename.txt -TotalCount 1
           echo "PACKAGEFILENAME=$filename" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: smplayer-portable-msvc
          path: packages\BUILD\output\${{ env.PACKAGEFILENAME }}
