name: Build SMPlayer on Mac OS
env:
  mplayer-url: https://github.com/smplayer-dev/mplayer-mod/releases/download/v1.4-71/mplayer.tar.bz2
  mpv-url: https://github.com/smplayer-dev/mpv-mod/releases/download/v0.33.1-45/mpv-bin.tar.bz2

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-10.15
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: smplayer-dev/smplayer
          path: packages/smplayer
          fetch-depth: 0

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          #version: '5.12.11'
          version: '5.15.2'
          host: 'mac'

      - name: Install QtWebkit
        run: |
            wget https://github.com/qtwebkit/qtwebkit/releases/download/qtwebkit-5.212.0-alpha4/qtwebkit-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z -O qtwebkit.7z
            7z x qtwebkit.7z -o$Qt5_Dir
 
      - name: Build smtube
        run: |
            git clone https://github.com/smplayer-dev/smtube.git packages/smtube
            cd packages/smtube
            ./get_svn_revision.sh
            cd src
            qmake
            make -j4

      - name: Install smtube            
        run: |
            mkdir packages/smplayer/src/smplayer.app/Contents/MacOS/
            cp packages/smtube/src/smtube.app/Contents/MacOS/smtube packages/smplayer/src/smplayer.app/Contents/MacOS/
            ls -lR packages/smplayer/src/smplayer.app/

      - name: Compile
        run: |
            cd packages/smplayer
            ./compile_mac.sh
            #ls -l

      - name: Install themes
        run: |
            git clone https://github.com/smplayer-dev/smplayer-themes.git packages/smplayer-themes
            cd packages/smplayer-themes
            make
            make install THEMES_PATH=../smplayer/package/SMPlayer.app/Contents/MacOS/themes

      - name: Install skins
        run: |
            git clone https://github.com/smplayer-dev/smplayer-skins.git packages/smplayer-skins
            cd packages/smplayer-skins
            make
            make install THEMES_PATH=../smplayer/package/SMPlayer.app/Contents/MacOS/themes

      - name: Install mplayer
        run: |
            wget ${{ env.mplayer-url }}
            tar -xvf mplayer.tar.bz2 -C packages/smplayer/package/SMPlayer.app --strip-components=1
            #ls -lR packages/smplayer/package/SMPlayer.app

      - name: Install mpv
        run: |
            wget ${{ env.mpv-url }}
            tar -xvf mpv-bin.tar.bz2 -C /tmp/
            cp /tmp/mpv.app/Contents/MacOS/mpv packages/smplayer/package/SMPlayer.app/Contents/MacOS/
            cp /tmp/mpv.app/Contents/MacOS/lib/* packages/smplayer/package/SMPlayer.app/Contents/MacOS/lib/

      - name: Create dmg
        run: |
            brew install create-dmg
            cd packages/smplayer
            ./create_dmg,sh
            ls -l package/

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: smplayer-macos
          path: packages/smplayer/package/*.dmg
