name: Build SMPlayer Windows

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: 'x64', 'portable': false }
          - { arch: 'win32', 'portable': false }
          - { arch: 'x64', 'portable': true }
          - { arch: 'win32', 'portable': true }          

    runs-on: windows-latest
    env:
      PORTABLE: ${{ matrix.config.portable }}
      
    steps:
      - name: Test
        run: |
            $env:PORTABLE
            if ($env:PORTABLE -eq $true) { "Portable" } else { "No portable" }
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install sources
        run: .\download_packages.cmd

      - name: Install mplayer and mpv
        run: .\uncompress_players.cmd

      - name: Install Qt (32 bit)
        if: ${{ matrix.config.arch == 'win32' }}
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: 'win32_mingw81'
          #tools: 'tools_mingw,8.1.0-1,qt.tools.win32_mingw810 tools_openssl_x86,1.1.1-1,qt.tools.openssl.win_x86'
          #tools: 'tools_mingw,8.1.0-1,qt.tools.win32_mingw810'

      - name: Install Qt (64 bit)
        if: ${{ matrix.config.arch == 'x64' }}
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: 'win64_mingw81'
          #tools: 'tools_openssl_x64,1.1.1-1,qt.tools.openssl.win_x64'
          #tools: 'tools_mingw,8.1.0-1,qt.tools.win64_mingw810'

      - name: Set mingw32 path
        if: ${{ matrix.config.arch == 'win32' }}
        run: echo "$env:IQTA_TOOLS\mingw810_32\bin\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Set mingw32 path (64 bit)
        if: ${{ matrix.config.arch == 'x64' }}
        run: echo "$env:IQTA_TOOLS\mingw810_64\bin\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Compile themes
        run: .\compile_themes.cmd

      - name: Compile smplayer
        run: |
            if ($env:PORTABLE -eq $true) {
              .\compile_smplayer.cmd pe
            } else {
              .\compile_smplayer.cmd
            }

      - name: Install
        run: |
            if ($env:PORTABLE -eq $true) {
              .\install.cmd pe
            } else {
              .\install.cmd
            }

      - name: Create installer
        if: ${{ matrix.config.portable == false }}
        run: |
           .\nsis.cmd
           $filename = Get-Content packages\BUILD\installer_filename.txt -TotalCount 1
           echo "PACKAGEFILENAME=$filename" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create 7z package
        if: ${{ matrix.config.portable == true }}
        run: |
           .\create_portable_package.cmd
           $filename = Get-Content packages\BUILD\portable_filename.txt -TotalCount 1
           echo "PACKAGEFILENAME=$filename" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGEFILENAME }}
          path: packages\BUILD\output\${{ env.PACKAGEFILENAME }}

      - name: Upload package to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: packages\BUILD\output\${{ env.PACKAGEFILENAME }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
