name: Build SMTube with Qt 5.6
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: 'x64' }
          - { arch: 'win32' }

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Qt 5.6 (32 bit)
        if: ${{ matrix.config.arch == 'win32' }}
        shell: bash
        run: |
            ./wget -nv https://github.com/smplayer-dev/smplayer-build/releases/download/qt5.6.3/Qt5.6.3_mingw493_32-563-p-dwarf2-opengl_dynamic.7z -O Qt5.6z
            7z x Qt5.6z -oQt5
            # Set environment variables
            export MinGW_Bin_Path=$GITHUB_WORKSPACE/Qt5/mingw32/bin
            export Qt_Bin_Path=$GITHUB_WORKSPACE/Qt5/mingw493_32-563-p-dwarf2/bin
            echo "MinGW_Bin_Path=$MinGW_Bin_Path" >> $GITHUB_ENV
            echo "Qt_Bin_Path=$Qt_Bin_Path" >> $GITHUB_ENV
            echo "$MinGW_Bin_Path" >> $GITHUB_PATH
            echo "$Qt_Bin_Path" >> $GITHUB_PATH

      - name: Install Qt 5.6 (64 bit)
        if: ${{ matrix.config.arch == 'x64' }}
        shell: bash
        run: |
            ./wget -nv https://github.com/smplayer-dev/smplayer-build/releases/download/qt5.6.3/Qt5.6.3_mingw493_64-563-p-seh-opengl_dynamic.7z -O Qt5.6z
            7z x Qt5.6z -oQt5
            # Set environment variables
            export MinGW_Bin_Path=$GITHUB_WORKSPACE/Qt5/mingw64/bin
            export Qt_Bin_Path=$GITHUB_WORKSPACE/Qt5/mingw493_64-563-p-seh/bin
            echo "MinGW_Bin_Path=$MinGW_Bin_Path" >> $GITHUB_ENV
            echo "Qt_Bin_Path=$Qt_Bin_Path" >> $GITHUB_ENV
            echo "$MinGW_Bin_Path" >> $GITHUB_PATH
            echo "$Qt_Bin_Path" >> $GITHUB_PATH

      - name: Build smtube
        run: |
            .\download_smtube.cmd
            .\build_smtube.cmd

      - name: Get installer name
        shell: bash
        run: |
            filename=`cd packages/smtube/setup/output/ ; ls smtube*.exe | head -1`
            echo "PACKAGEFILENAME=$filename" >> $GITHUB_ENV

      - name: Rename package
        shell: bash
        run: |
            PACKAGEFILENAME=${{ env.PACKAGEFILENAME }}
            extension="${PACKAGEFILENAME##*.}"
            filename="${PACKAGEFILENAME%.*}"
            new_filename="$filename-qt5.6.$extension"
            cd packages/smtube/setup/output/
            mv $PACKAGEFILENAME $new_filename
            echo "PACKAGEFILENAME=$new_filename" >> $GITHUB_ENV

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGEFILENAME }}
          path: packages\smtube\setup\output\smtube*.exe
