name: Build SMPlayer on Mac OS
env:
  mplayer-url: https://github.com/smplayer-dev/mplayer-mod/releases/download/v1.4-71/mplayer.tar.bz2
  mpv-url: https://github.com/smplayer-dev/mpv-mod/releases/download/v0.33.1-43/mpv-bin.tar.bz2

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-10.15
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: smplayer-dev/smplayer
          path: packages/smplayer

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.11'
          host: 'mac'

      - name: Compile
        run: |
            cd packages/smplayer
            ./compile_mac.sh
            #ls -l

      - name: Install mplayer
        run: |
            wget ${{ env.mplayer-url }}
            tar -xvf mplayer.tar.bz2 -C packages/smplayer/package/SMPlayer.app --strip-components=1
            #ls -lR packages/smplayer/package/SMPlayer.app

      - name: Install mpv
        run: |
            wget ${{ env.mpv-url }}
            tar -xvf mpv-bin.tar.bz2 -C /tmp/
            cp /tmp/mpv.app/Contents/MacOS/mpv packages/smplayer/package/SMPlayer.app/Contents/MacOS/
            cp /tmp/mpv.app/Contents/MacOS/lib/* packages/smplayer/package/SMPlayer.app/Contents/MacOS/lib/

      - name: Create dmg
        run: |
            brew install create-dmg
            cd packages/smplayer
            ./create_dmg,sh
            ls -l package/

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: smplayer-mac
          #path: packages/smplayer/package/
          path: packages/smplayer/package/SMPlayer.dmg
