name: Build appimage

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    container: wachii/ubuntu-qt512:16.04
    #runs-on: ubuntu-18.04

    steps:
      - name: Install sources
        run: git clone https://github.com/smplayer-dev/smplayer.git smplayer

      - name: Install linuxdeployqt
        run: |
            wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -O linuxdeployqt.AppImage 
            chmod 755 linuxdeployqt.AppImage

      - name: Install development packages
        if: ${{false}}
        run: |
            sudo apt-get update
            #sudo apt-get install zlib1g-dev fakeroot build-essential devscripts debhelper g++
            #sudo apt-get install qtbase5-dev qt5-qmake qt5-default libqt5opengl5-dev qttools5-dev-tools qtbase5-private-dev
            sudo apt-get -y install libxcb-xinerama0 libgl1-mesa-dev
            #sudo apt-get -y remove qtbase5-dev qt5-qmake qt5-default libqt5opengl5-dev qttools5-dev-tools qtbase5-private-dev libqt5webkit5-dev
            #sudo apt-get -y install python3-pip


      - name: Install development packages
        #if: ${{false}}
        run: |
            sudo apt-get update
            sudo apt-get install qtbase5-dev qt5-qmake qt5-default libqt5opengl5-dev qttools5-dev-tools qtbase5-private-dev
            sudo apt-get -y install libxcb-xinerama0 libgl1-mesa-dev
            
      - name: Install Qt
        if: ${{false}}
        run: |
            sudo add-apt-repository ppa:beineri/opt-qt-5.12.2-xenial -y
            sudo apt-get update
            sudo apt-get -y install qt512-meta-full libgl1-mesa-dev
            source /opt/qt512/bin/qt512-env.sh || true

      - name: Install Qt
        if: ${{false}}
        uses: jurplel/install-qt-action@v2
        with:
          host: 'linux'

      - name: Get version
        run: |
            cd smplayer
            ./get_version.sh
            VERSION=`cat version`
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Compile smplayer
        shell: bash
        run: |
            test -x /opt/qt512/bin/qt512-env.sh && source /opt/qt512/bin/qt512-env.sh || true
            cd smplayer
            ./compile_appimage.sh

      - name: Install mpv
        run: |
            sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4
            sudo apt-get update
            wget https://github.com/smplayer-dev/mpv-mod/releases/download/v0.33.1-52/mpv_0.33.1-1.xenial_amd64.deb
            sudo apt-get -y install ./mpv_0.33.1-1.xenial_amd64.deb
            cp /usr/bin/mpv smplayer/appdir/usr/bin/
            ls -lR appdir

      - name: Create package
        shell: bash
        run: |
            test -x /opt/qt512/bin/qt512-env.sh && source /opt/qt512/bin/qt512-env.sh || true
            cd smplayer
            ../linuxdeployqt.AppImage appdir/usr/share/applications/smplayer.desktop \
                                     -executable=appdir/usr/bin/mpv -bundle-non-qt-libs \
                                     -appimage --appimage-extract-and-run
    
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: smplayer-appimage
          path: smplayer/*.AppImage
