name: Build Appimage
  
on: workflow_dispatch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          #- { container: 'wachii/xenial-qt:5.15.2', qt: '5.15', qt-env: '/opt/qt515/bin/qt515-env.sh' }
          #- { container: 'wachii/ubuntu-qt:21.04', qt: '5.12', qt-env: '/opt/qt512/bin/qt512-env.sh' }
          - { container: 'a12e/docker-qt:5.14-gcc_64', qt: '5.14', qt-env: '' }

    runs-on: ubuntu-latest
    container: ${{ matrix.config.container }}
    #container: wachii/xenial-qt:5.12
    #container: wachii/xenial-qt:5.15.2
    #runs-on: ubuntu-18.04

    steps:
      - name: Install sources
        run: |
            cd
            pwd
            git clone https://github.com/smplayer-dev/smplayer.git smplayer

      - name: Install linuxdeployqt
        if: ${{ matrix.config.qt-env != '' }}
        run: |
            wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -O linuxdeployqt.AppImage 
            chmod 755 linuxdeployqt.AppImage

      - name: Install development packages
        if: ${{false}}
        run: |
            sudo apt-get update
            sudo apt-get install qtbase5-dev qt5-qmake qt5-default libqt5opengl5-dev qttools5-dev-tools qtbase5-private-dev
            sudo apt-get -y install libxcb-xinerama0 libgl1-mesa-dev

      - name: Install add-apt-repository
        if:  ${{ matrix.config.qt-env == '' }}
        run: |
            sudo apt-get update
            sudo apt-get install software-properties-common
  
      - name: Get version
        run: |
            cd smplayer
            ./get_version.sh
            VERSION=`cat version`
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Compile smplayer
        shell: bash
        run: |
            test -x ${{matrix.config.qt-env}} && source ${{matrix.config.qt-env}} || true
            cd smplayer
            ./compile_appimage.sh

      - name: Install mpv
        run: |
            sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4
            sudo apt-get update
            wget https://github.com/smplayer-dev/mpv-mod/releases/download/v0.33.1-52/mpv_0.33.1-1.xenial_amd64.deb
            sudo apt-get -y install ./mpv_0.33.1-1.xenial_amd64.deb
            cp /usr/bin/mpv smplayer/appdir/usr/bin/

      - name: Install mplayer
        run: |
            wget https://github.com/smplayer-dev/mplayer-mod/releases/download/v1.4-71/mplayer_1.4-1.xenial_amd64.deb
            sudo apt-get -y install ./mplayer_1.4-1.xenial_amd64.deb
            cp /usr/bin/mplayer smplayer/appdir/usr/bin

      - name: Create package
        if: ${{ matrix.config.qt-env != '' }}
        shell: bash
        run: |
            test -x ${{matrix.config.qt-env}} && source ${{matrix.config.qt-env}} || true
            cd smplayer
            ../linuxdeployqt.AppImage appdir/usr/share/applications/smplayer.desktop \
                                     -extra-plugins=platforms/libqwayland-egl.so,platforms/libqwayland-xcomposite-egl.so,platforms/libqwayland-generic.so,platforms/libqwayland-xcomposite-glx.so \
                                     -executable=appdir/usr/bin/mpv \
                                     -executable=appdir/usr/bin/mplayer \
                                     -bundle-non-qt-libs \
                                     -appimage --appimage-extract-and-run

      - name: Create package
        if: ${{ matrix.config.qt-env == '' }}
        run: |
            cd smplayer
            linuxdeployqt appdir/usr/share/applications/smplayer.desktop \
                          -executable=appdir/usr/bin/mpv \
                          -executable=appdir/usr/bin/mplayer \
                          -bundle-non-qt-libs \
                          -appimage --appimage-extract-and-run         
        
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: smplayer-${{env.VERSION}}-${{matrix.config.qt}}
          path: smplayer/*.AppImage
